spring:
  datasource:
    username: accounting.files
    password: accounting.files
    url: jdbc:mysql://localhost:3306/accounting.files
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always